### ISSUE TITLE
pip install & clone install

### ISSUE THREAD

**Issue by sparkX5** [jawahar273/practNLPTools-lite#168]
Hi, I have got some problems when I install the pntl on Windows and Python3.7.
Is there any difference between _pip install pntl_ and _python setup.py install_ from the repository?
Because when I install it from setup.py, the folder _site_packages_ will miss a lot of files like _tools.py_, which only has the folder _pntl-version_version_0.3.5_-py3.7.egg_ and it seems uncompleted.

**************************************************************************************************************
`PS D:\python\Lib\practNLPtools\practNLPTools-lite-master> python setup.py install
D:\python\lib\site-packages\setuptools\dist.py:406: UserWarning: The version specified ("version='version='0.3.5''") is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running install
running bdist_egg
running egg_info
writing pntl.egg-info\PKG-INFO
writing dependency_links to pntl.egg-info\dependency_links.txt
writing entry points to pntl.egg-info\entry_points.txt
writing requirements to pntl.egg-info\requires.txt
writing top-level names to pntl.egg-info\top_level.txt
reading manifest file 'pntl.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'HISTORY.rst'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
warning: no files found matching '*.rst' under directory 'docs'
warning: no files found matching 'conf.py' under directory 'docs'
warning: no files found matching 'Makefile' under directory 'docs'
warning: no files found matching 'make.bat' under directory 'docs'
warning: no files found matching '*.jpg' under directory 'docs'
writing manifest file 'pntl.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\pntl
creating build\bdist.win-amd64\egg\pntl\senna
copying build\lib\pntl\senna\__init__.py -> build\bdist.win-amd64\egg\pntl\senna
byte-compiling build\bdist.win-amd64\egg\pntl\senna\__init__.py to __init__.cpython-37.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying pntl.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying pntl.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pntl.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pntl.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pntl.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying pntl.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pntl.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
creating 'dist\pntl-version_version_0.3.5_-py3.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing pntl-version_version_0.3.5_-py3.7.egg
creating d:\python\lib\site-packages\pntl-version_version_0.3.5_-py3.7.egg
Extracting pntl-version_version_0.3.5_-py3.7.egg to d:\python\lib\site-packages
Adding pntl version-version-0.3.5- to easy-install.pth file
Installing pntl-script.py script to D:\python\Scripts
Installing pntl.exe script to D:\python\Scripts

Installed d:\python\lib\site-packages\pntl-version_version_0.3.5_-py3.7.egg
Processing dependencies for pntl===version-version-0.3.5-
Searching for python-dotenv==0.10.1
Best match: python-dotenv 0.10.1
Processing python_dotenv-0.10.1-py3.7.egg
python-dotenv 0.10.1 is already the active version in easy-install.pth
Installing dotenv-script.py script to D:\python\Scripts
Installing dotenv.exe script to D:\python\Scripts

Using d:\python\lib\site-packages\python_dotenv-0.10.1-py3.7.egg
Searching for pyyaml==4.2b4
Best match: pyyaml 4.2b4
Processing pyyaml-4.2b4-py3.7-win-amd64.egg
pyyaml 4.2b4 is already the active version in easy-install.pth

Using d:\python\lib\site-packages\pyyaml-4.2b4-py3.7-win-amd64.egg
Searching for click==7.0
Best match: click 7.0
Processing click-7.0-py3.7.egg
click 7.0 is already the active version in easy-install.pth

Using d:\python\lib\site-packages\click-7.0-py3.7.egg
Searching for colorama==0.4.1
Best match: colorama 0.4.1
Processing colorama-0.4.1-py3.7.egg
colorama 0.4.1 is already the active version in easy-install.pth

Using d:\python\lib\site-packages\colorama-0.4.1-py3.7.egg
Finished processing dependencies for pntl===version-version-0.3.5-`
**************************************************************************************************************

And when i install it from the pip, there will be _tools.py_. But its version is _pntl-0.2.4_ . 
If i use the version _pntl-0.2.4_ , is there any need to save the repository as it seems not used?

When i use the version _pntl-0.2.4_ to import _Annotator_, it meets new problems.

**************************************************************************************************************
`PS D:\patent mining\code\SAO extract\SAO> python practNLPToolsTest.py
****************************************************************************************************
default values:
senna path:

Dependencie parser:
 D:\python\lib\site-packages\pntl\
Stanford parser clr java -cp stanford-parser.jar edu.stanford.nlp.trees.EnglishGrammaticalStructure -treeFile in.parse -collapsed
****************************************************************************************************
Traceback (most recent call last):
  File "practNLPToolsTest.py", line 10, in <module>
    result = annotator.get_annoations( text )["srl"]
  File "D:\python\lib\site-packages\pntl\tools.py", line 408, in get_annoations
    senna_tags = self.get_senna_tag(sentence).decode()
  File "D:\python\lib\site-packages\pntl\tools.py", line 329, in get_senna_tag
    os.chdir(package_directory)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ''`
**************************************************************************************************************

Thank you a lot !!

**Comment by jawahar273** [comment]
need to give senna path in annotator_api
https://pntl.readthedocs.io/en/master/annotator_api.html.

Actually the pip(stable version) and the github master(new features and under development) are diffrent
version. Yes.

Also my current version of github is 0.3.6 check that out.
